---
title: "Salinity Data"
author: "Aries Socrates"
date: '2022-06-03'
output: html_document
---

## 1. Download data
Downloaded to Chapter 2 folder

## 2. Create new RMD file
Done!

## 3. Read data into R
```{r}
Data = read.csv("DataSalinity_SFbar_FortPoint.csv")

summary(Data)
```


## 4. Make sure dates are recognized as dates

```{r}
#install.packages("chron")
library(chron)

Data$Date = as.chron(Data$Date) #doing this to overwrite the original (so that r can recognize them as dates and not just as characters)
```


```{r}
summary(Data)

```

## 5. Plot date vs salinity

```{r}
plot(x = Data$Date, y = Data$Salinity, col = "purple")
```


## 6. Add line for Oct 24th 2021

```{r}
plot(x = Data$Date, y = Data$Salinity, col = "purple")
abline(v = as.chron("10/24/2021"))
```

## ggplot facet_wrap
```{r}
#install.packages("ggplot2")
library(ggplot2)

#myplot is the name of our plot, ggplot is the command
#Data is our own data file, aes defines what range we are using
#We are using Date and Salinity
myplot = ggplot(Data, aes(Date, WaterTemp))
myplot + geom_point(col = "red")+
  scale_x_chron()+
  geom_vline(xintercept = as.chron("10/24/2021"), linetype = 2, color = "blue", size = 1)+ #we just added a blue line in the date, and the date was chronologically added using the as.chron() function, the size was the thickness
  facet_wrap(~Location) #plots both for fortpoint and SF
```


##ggplot color for location

```{r}
#install.packages("ggplot2")
library(ggplot2)

#myplot is the name of our plot, ggplot is the command
#Data is our own data file, aes defines what range we are using
#We are using Date and Salinity
myplot = ggplot(Data, aes(Date, WaterTemp))
myplot + geom_point(aes(col = Location), alpha = 0.1)+
  scale_x_chron()+
  geom_vline(xintercept = as.chron("10/24/2021"), linetype = 2, color = "blue", size = 1)
```